In [3]:
#I
import numpy as np

# Creating a 1D array from 0 to 9
array_1 = np.arange(10)

print(array_1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
#II
import numpy as np

# List to convert
list_data = [3.14, 2.17, 0, 1, 2]

# Convert to NumPy array and change data type to integer
array_2 = np.array(list_data).astype(int)

print(array_2)

[3 2 0 1 2]


In [5]:
#III Creating a 3x3 array with values from 1 to 9
array_3 = np.arange(1, 10).reshape(3, 3)

print(array_3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#IV

# Creating a 2D array of shape (4, 5) filled with random numbers
array_4 = np.random.rand(4, 5)

print(array_4)

[[0.06346195 0.43072106 0.54257513 0.27435269 0.2276171 ]
 [0.84955116 0.22216804 0.32910062 0.12322809 0.91823348]
 [0.99116068 0.0533252  0.31606798 0.14077666 0.32524967]
 [0.02883535 0.45757394 0.71557571 0.24395889 0.34120202]]


In [7]:
#V
# Sample 2D array
array_5 = np.array([[10, 11, 12, 13, 14],
                  [20, 21, 22, 23, 24],
                  [30, 31, 32, 33, 34]])

# Select the second row (index 1)
second_row = array_5[1]

print(second_row)

[20 21 22 23 24]


In [8]:
#VI
# Creating a 1D array from 0 to 9
array_6 = np.arange(10)

# Reversing the array
reversed_array = array_6[::-1]

print(reversed_array)

[9 8 7 6 5 4 3 2 1 0]


In [11]:
#VII
# Creating a 4x4 identity matrix
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
#VII - B
# Creating a 4x4 identity matrix with integer values
identity_matrix = np.eye(4, dtype=int)

print(identity_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [13]:
#VIII
# Creating a 1D array from 0 to 9
array_8 = np.arange(10)

# Calculating the sum
sum_of_array = np.sum(array_8)

# Calculating the average (mean)
average_of_array = np.mean(array_8)

print(f"Sum: {sum_of_array}, Average: {average_of_array}")

Sum: 45, Average: 4.5


In [14]:
#IX

# Creating a 1D array with elements from 1 to 20
array_9 = np.arange(1, 21)

# Reshaping it into a 4x5 matrix
reshaped_array = array_9.reshape(4, 5)

print(reshaped_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [15]:
#IX - B
# Reshaping the 4x5 matrix back into a 1D array
reshaped_back_to_1d = reshaped_array.reshape(-1)

print(reshaped_back_to_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [16]:
#X

# Creating a 1D array from 0 to 9
array_10 = np.arange(10)

# Extracting all odd numbers using a condition
odd_numbers = array_10[array_10 % 2 != 0]

print(odd_numbers)

[1 3 5 7 9]


In [17]:
#I Gold

# Creating a 5x5 array with random values between 0 and 1
random_array = np.random.rand(5, 5)

# Finding the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print(f"Min: {min_value:.2f}, Max: {max_value:.2f}")

Min: 0.08, Max: 0.98


In [18]:
#II Gold

# Creating a 3x3 matrix with random values
matrix = np.random.rand(3, 3)

# Calculate the mean and standard deviation of the matrix
mean = np.mean(matrix)
std_dev = np.std(matrix)

# Normalize the matrix
normalized_matrix = (matrix - mean) / std_dev

print(normalized_matrix)

[[-1.5837276   2.16988763  0.11526376]
 [ 0.39788593 -0.64904479 -0.1843387 ]
 [-0.9427647   0.19932339  0.47751508]]


In [19]:
#III Gold
# Creating a 1D array of 50 evenly spaced elements between 0 and 10 (inclusive)
evenly_spaced_array = np.linspace(0, 10, 50)

print(evenly_spaced_array)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [20]:
#IV
matrix_1 = np.random.rand(5, 3)

# Creating a 3x2 matrix
matrix_2 = np.random.rand(3, 2)

# Performing matrix multiplication
result = np.dot(matrix_1, matrix_2)  # Alternatively, you can use: result = matrix_1 @ matrix_2

print(result)

[[0.69335904 0.60136332]
 [0.37362741 0.33271656]
 [0.93406762 0.82818029]
 [0.76291651 0.80494243]
 [0.82549228 0.71866707]]


In [21]:
# Creating a 4x2 matrix
matrix_A = np.random.rand(4, 2)

# Creating a 2x3 matrix
matrix_B = np.random.rand(2, 3)

# Performing matrix multiplication
result = np.dot(matrix_A, matrix_B)  # Alternatively, you can use: result = matrix_A @ matrix_B

# Displaying the result
print("Matrix A (4x2):")
print(matrix_A)
print("\nMatrix B (2x3):")
print(matrix_B)
print("\nResult of Matrix A * Matrix B (4x3):")
print(result)

Matrix A (4x2):
[[0.74071691 0.20378705]
 [0.64516475 0.3784599 ]
 [0.75568512 0.11078467]
 [0.65509791 0.04578997]]

Matrix B (2x3):
[[0.86663428 0.53343717 0.38598873]
 [0.30904579 0.95327696 0.42791385]]

Result of Matrix A * Matrix B (4x3):
[[0.70491019 0.58939143 0.37311168]
 [0.67608332 0.70493196 0.41097456]
 [0.68914016 0.508719   0.33909223]
 [0.5818815  0.3931041  0.27245458]]
